<?php

function com_starter_staff_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'com_starter_staff') . '/views',
    'template path' => drupal_get_path('module', 'com_starter_staff') . '/views/themes',
  );
}

function com_starter_staff_form_com_starter_admin_alter(&$form, &$form_state) {

	$form['com_starter_settings']['com_starter_staff'] = array(
		'#title' => t('Staff'),
		'#type' => 'fieldset',
		'#weight' => count($form['com_starter_settings']) * 3,
	);

	$form['com_starter_settings']['com_starter_staff']['com_starter_staff_page_header'] = array(
		'#default_value' => variable_get('com_starter_staff_page_header', ''),
	    '#type' => 'managed_file',
	    '#title' => t('Staff Page Header'),
	    '#weight' => -10,
	    '#upload_location' => 'public://com_starter_staff_page_header/',
	);
}


// lets obfuscate the email address and then put it back with js
function com_starter_staff_views_pre_render(&$view) {
	if ( $view->name =="staff" && $view->current_display == "page" ) {
		foreach( $view->result as &$staff ) {			
			$email = $staff->field_field_email[0]['rendered']['#markup'];
			$staff->field_field_email[0]['rendered']['#markup'] = $staff->field_field_email[0]['raw']['email'] = str_replace("@", "/", $email);
		}
	}
}


function com_starter_staff_block_info() {
	$blocks['staff_info'] = array(
    	'info' => t('Staff Info'),
		'cache' => DRUPAL_NO_CACHE
	);

	return $blocks;
}




function com_starter_staff_block_view($delta = '') {

	$block = array();

	switch ($delta) {
    	case 'staff_info':
    	
    		$staff_member = menu_get_object();			
						
			$image = field_view_field('node', $staff_member, 'field_staff_graphic', 'full');
			$position = field_view_field('node', $staff_member, 'field_position', 'full');
			$office = field_view_field('node', $staff_member, 'field_office', 'full');
			$phone_number = field_view_field('node', $staff_member, 'field_phone_number', 'full');
			$email = field_view_field('node', $staff_member, 'field_email', 'full');
			
				
			$block['subject'] = NULL;
			$block['content'] = //array( 
				//'#markup' => $photo . $position . $office . $phone_number . $email,
				render($image) . render($position) . render($office) . render($phone_number) . render($email);
			//);

			break;
	}
	
	return $block;
}