<footer id="footer">
	<div id="footer-top">
		<div class="row">
			<ul class="address column">
				<li>
					<h4>Kentfield Campus</h4>
					835 College Ave.<br />
					Kentfield, CA 94904<br />
					(415) 457-8811<br />
					<a href="https://goo.gl/maps/a59H1" class="map-icon">Google Map</a> | <a href="<?php com_get_multi_site_base_url('campuses.marin.edu/campus-maps'); ?>" >Campus Map</a>
				</li>
				<li>
					<h4>Indian Valley Campus</h4>
					1800 Ignacio Blvd.<br />
					Novato, CA 94949<br />
					(415) 883-2211<br />
					<a href="https://goo.gl/maps/yBkRc" class="map-icon">Google Map</a> | <a href="<?php com_get_multi_site_base_url('campuses.marin.edu/campus-maps#ivc'); ?>">Campus Map</a>
				</li>				
			</ul>
			<ul class="links column">
				<li><a href="<?php com_get_multi_site_base_url('accreditation.marin.edu'); ?>">Accreditation</a></li>
				<li><a href="<?php com_get_multi_site_base_url('marin.edu/ada-accessibility'); ?>">ADA Accessibility</a></li>
				<li><a href="https://www.boarddocs.com/ca/marin/Board.nsf/Public">Board Meeting Agenda</a></li>
				<li><a href="<?php com_get_multi_site_base_url('policies.marin.edu'); ?>">Campus Policies</a></li>
				<li><a href="<?php com_get_multi_site_base_url('marin.edu/consumer-information'); ?>">Consumer Information</a></li>
				<li><a href="<?php com_get_multi_site_base_url('policies.marin.edu/discrimination-harassment'); ?>">Discrimination, Harassment & Title IX</a></li>
			</ul>
			<ul class="links column">
				<li><a href="<?php com_get_multi_site_base_url('academics.marin.edu'); ?>">Academic Programs</a></li>
				<li><a href="<?php com_get_multi_site_base_url('marin.edu/schedule'); ?>">Class Schedule & Catalogs</a></li>
				<li><a href="https://marin.elumenapp.com/public/">Course Outline of Record</a></li>
				<li><a href="https://marin.elumenapp.com/catalog/current/program-and-course-descriptions">Degrees &amp; Certificates</a></li>
				<li><a href="https://netapps.marin.edu/Apps/Directory/ScheduleSearch.aspx">Schedule Search</a></li>
			</ul> 
			<ul class="links column">
				<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/cdp'); ?>">Child Development Program</a></li>
				<li><a href="<?php com_get_multi_site_base_url('es.marin.edu/registration/enrollment-priority'); ?>">Enrollment Priority</a></li>
				<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/eops-calworks'); ?>">EOPS/CARE & CalWORKs</a></li>
				<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/outreach'); ?>">Outreach</a></li>
				<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/health-services'); ?>">Student Health Services</a></li>
				<li><a href="<?php com_get_multi_site_base_url('initiatives.marin.edu/ztc'); ?>">Zero Textbook Cost Program</a></li>
			</ul>
			<ul class="links column">
				<li><a href="https://netapps.marin.edu/Apps/Directory/EmployeeSearch.aspx">Employee Directory</a></li>
				<li><a href="http://jobs.marin.edu">Employment</a></li>
				<li><a href="<?php com_get_multi_site_base_url('marin.edu/facilities-rental'); ?>">Facilities Rental</a></li>
				<li><a href="<?php com_get_multi_site_base_url('forms.marin.edu'); ?>">Forms</a></li>
			</ul>									
		</div>
	</div>
	<div id="footer-bottom">
		<div class="row">
			<div id="copyright" class="column">
				<h3>College of Marin</h3>
				Copyright &copy; <?php print date('Y'); ?> Marin Community College District. All rights reserved.
			</div>
			<?php print $com_foundation_social_links; ?>
		</div><!-- end row -->
	</div>
</footer>
