<header id="header">
	<div class="row top">
		<div class="column">
			<div id="logo-site-name">
				<?php print $linked_logo; ?>
				<?php if ($site_name): print $site_name; endif; ?>
			</div>
			<span class="hamburger-menu" data-target="#school-nav"></span>
		</div>
	</div><!-- // row.top -->
	
	<div id="nav-wrapper">
	
		<nav id="school-nav">
			<div class="row">
			<div class="right">
				<ul id="quick-links" class="clearfix">
					<li><a href="http://mycom.marin.edu">MyCOM</a></li>
					<li><a href="#main" id="skip-to-content">Skip to Content</a></li>
					<li><a href="<?php com_get_multi_site_base_url('campuses.marin.edu/campus-maps'); ?>" id="maps-link-new">Maps</a></li>
				</ul>
	
				<gcse:search id="header-search"></gcse:search>
			</div>
			</div>

			<div id="top-nav">
				<ul class="row">
					<li><a href="<?php com_get_multi_site_base_url('marin.edu/admissions'); ?>">Admissions</a></li>
					<li><a href="<?php com_get_multi_site_base_url('marin.edu/academics'); ?>">Academics</a></li>
					<li><a href="<?php com_get_multi_site_base_url('marin.edu/students'); ?>">Students</a></li>
					<li><a href="<?php com_get_multi_site_base_url('marin.edu/campus-life'); ?>">Campus Life</a></li>
					<li><a href="<?php com_get_multi_site_base_url('marin.edu/faculty-staff'); ?>">Faculty/Staff</a></li>
					<li><a href="<?php com_get_multi_site_base_url('marin.edu/administration'); ?>">Administration</a></li>
					<li><a href="<?php com_get_multi_site_base_url('marin.edu/about-com'); ?>">About COM</a></li>
					<li><a href="<?php com_get_multi_site_base_url('advancement.marin.edu'); ?>">Support COM</a></li>
				</ul>
			</div>
	
			<div id="sub-nav">
				<div class="row">
					<ul>
						<li class="home"><a href="<?php com_get_multi_site_base_url('marin.edu/admissions'); ?>">Admissions</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/apply'); ?>">Apply for Admission</a></li>
						<li><a href="<?php com_get_multi_site_base_url('es.marin.edu'); ?>">Enrollment Services</a></li>
						<li><a href="<?php com_get_multi_site_base_url('es.marin.edu/financial-aid'); ?>">Financial Aid</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/high-school-programs'); ?>">High School Programs</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/orientation'); ?>">Orientation</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/paying-college'); ?>">Paying for College</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/assessment'); ?>">Placement Process</a></li>
						<li><a href="http://mycom.marin.edu/">Register for Classes</a></li>
					</ul>
					<ul>
						<li class="home"><a href="<?php com_get_multi_site_base_url('marin.edu/academics'); ?>">Academics</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/events/academic-calendar'); ?>">Academic Calendar</a></li>
						<li><a href="<?php com_get_multi_site_base_url('academics.marin.edu'); ?>">Academic Programs</a></li>
						<li><a href="<?php com_get_multi_site_base_url('cte.marin.edu'); ?>">Career Education</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/schedule'); ?>">Class Schedules &amp; Catalogs</a></li>
						<li><a href="http://marincommunityed.augusoft.net/">Community Education</a></li>
						<li><a href="https://marin.elumenapp.com/public/">Course Outline of Record</a></li>
						<li><a href="https://marin.elumenapp.com/catalog/current/program-and-course-descriptions">Degrees &amp; Certificates</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ol.marin.edu'); ?>">Online Learning</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/learning-communities'); ?>">Learning Communities</a></li>
					</ul>
					<ul>
						<li class="home"><a href="<?php com_get_multi_site_base_url('marin.edu/students'); ?>">Students</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/campus-store'); ?>">Bookstore</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/counseling'); ?>">Counseling</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/career-services'); ?>">Career Services</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/international-students'); ?>">International Students</a></li>
						<li><a href="<?php com_get_multi_site_base_url('library.marin.edu'); ?>">Library</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/sas'); ?>">Student Accessibility Services</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu'); ?>">Student Services</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/tcc'); ?>">Transfer Center</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/tutoring-labs'); ?>">Tutoring / Labs</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/veterans'); ?>">Veteran Services</a></li>
					</ul>
					<ul>
						<li class="home"><a href="<?php com_get_multi_site_base_url('marin.edu/campus-life'); ?>">Campus Life</a></li>
						<li><a href="http://athletics.marin.edu">Athletics</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/comcard'); ?>">COM Card / Student ID</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/community-hour'); ?>">COMmunity Hour</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/events'); ?>">Events & Activities</a></li>
						<li><a href="<?php com_get_multi_site_base_url('gallery.marin.edu'); ?>">Fine Arts Gallery</a></li>
						<li><a href="<?php com_get_multi_site_base_url('pa.marin.edu'); ?>">Performing Arts</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/science-museum'); ?>">Science Museum</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/saa/ascom'); ?>">Student Government</a></li>
						<li><a href="<?php com_get_multi_site_base_url('ss.marin.edu/saa/student-clubs'); ?>">Student Organizations</a></li>
					</ul>
					<ul> 
						<li class="home"><a href="<?php com_get_multi_site_base_url('marin.edu/faculty-staff'); ?>">Faculty/Staff</a></li>
						<li><a href="<?php com_get_multi_site_base_url('as.marin.edu'); ?>">Academic Senate</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/assessment-and-program-review'); ?>">Assessment/Program Review</a></li>						
						<li><a href="<?php com_get_multi_site_base_url('cs.marin.edu'); ?>">Classified Senate</a></li>
						<li><a href="<?php com_get_multi_site_base_url('as.marin.edu/cc'); ?>">Curriculum Committee</a></li>
						<li><a href="https://netapps.marin.edu/Apps/Directory/EmployeeSearch.aspx">Employee Directory</a></li>
						<li><a href="<?php com_get_multi_site_base_url('as.marin.edu/handbook'); ?>">Faculty Handbook</a></li>
						<li><a href="<?php com_get_multi_site_base_url('gov.marin.edu'); ?>">Participatory Governance</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/professional-learning'); ?>">Professional Learning</a></li>
						<li><a href="<?php com_get_multi_site_base_url('cs.marin.edu/classified-professionals-handbook'); ?>">Staff Handbook</a></li>
					</ul>
					<ul>
						<li class="home"><a href="<?php com_get_multi_site_base_url('marin.edu/administration'); ?>">Administration</a></li>
						<li><a href="<?php com_get_multi_site_base_url('police.marin.edu'); ?>">Campus Police</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/college-operations'); ?>">Administrative Services</a></li>
						<li><a href="<?php com_get_multi_site_base_url('fiscal.marin.edu'); ?>">Fiscal Services</a></li>
						<li><a href="<?php com_get_multi_site_base_url('hr.marin.edu'); ?>">Human Resources</a></li>
						<li><a href="<?php com_get_multi_site_base_url('it.marin.edu'); ?>">Information Technology</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/maintenance-operations'); ?>">Maintenance &amp; Operations</a></li>
						<li><a href="<?php com_get_multi_site_base_url('president.marin.edu'); ?>">Office of the President</a></li>
						<li><a href="<?php com_get_multi_site_base_url('prie.marin.edu'); ?>">Planning &amp; Research</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/student-learning-services'); ?>">Student Learning/Success</a></li>
					</ul>
					<ul>
						<li class="home"><a href="<?php com_get_multi_site_base_url('marin.edu/about-com'); ?>">About COM</a></li>
						<li><a href="<?php com_get_multi_site_base_url('accreditation.marin.edu'); ?>">Accreditation</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/board-trustees'); ?>">Board of Trustees</a></li>
						<li><a href="<?php com_get_multi_site_base_url('prie.marin.edu/emp'); ?>">Educational Master Plan</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/fast-facts'); ?>">Fast Facts</a></li>
						<li><a href="<?php com_get_multi_site_base_url('legacy.marin.edu'); ?>">History &amp; Highlights</a></li>
						<li><a href="http://measurebcom.org">Measure B</a></li>
						<li><a href="<?php com_get_multi_site_base_url('marin.edu/mission'); ?>">Mission</a></li>
						<li><a href="<?php com_get_multi_site_base_url('policies.marin.edu'); ?>">Policies &amp; Procedures</a></li>
					</ul>
					<ul>
						<li class="home"><a href="<?php com_get_multi_site_base_url('advancement.marin.edu'); ?>">Support COM</a></li>
						<li><a href="<?php com_get_multi_site_base_url('alumni.marin.edu'); ?>">Alumni Connections</a></li> 
						<li><a href="<?php com_get_multi_site_base_url('advancement.marin.edu/establishing-student-scholarship'); ?>">Establish a Scholarship</a></li>
						<li><a href="https://secure.everyaction.com/avudBiwSqUivqS4RZ_56Yw2">Giving to COM</a></li>
						<li><a href="<?php com_get_multi_site_base_url('advancement.marin.edu/pillars-philanthropy'); ?>">Pillars of Philanthropy</a></li>
						<li><a href="<?php com_get_multi_site_base_url('advancement.marin.edu/1926-legacy-society'); ?>">Planned Giving</a></li>
						<li><a href="<?php com_get_multi_site_base_url('advancement.marin.edu/presidents-circle'); ?>">President's Circle</a></li>
					</ul>
					<a href="#" id="touch-nav-back">&lt; Back</a>
				</div>
			</div>
		</nav>
		
		
		<?php if (!empty($page['navigation'])): ?>
		<!--// #navigation -->
		<section id="navigation">
			<div class="row">
				<div class="large-12 column">
					<?php print render($page['navigation']); ?>
				</div>
			</div>
		</section><!--// #navigation -->
		<?php endif; ?>
	
	</div>
	
</header>